[package]
name = "server"
version = "0.1.0"
edition = "2024"
[dependencies]
rand = "0.10.2"
bevy_ecs = "0.19.1"
bevy_app = "0.19.1"
bevy_math = "0.19.1"
bevy_time = "0.19.1"
bevy_state = "0.19.1"
bevy_internal = "0.19.1"
bevy_replicon = { version = "0.43.0", default-features = false, features = ["server"] }
bevy_replicon_renet = { version = "0.19.0", default-features = false, features = ["server","renet_netcode"] }
shared = { version = "0.1.0", path = "../shared" }
